### ISSUE TITLE
Missing Residues

### ISSUE THREAD

**Issue by Kloppel** [Kloppel/helpers#9]
Do we provide a solution for missing residues, e.g. warning the user if we automatically renumber residues?
thought for later.

**Comment by Nereumobu** [comment]
#6 I think we could give either of two options:

a) Rewrite the residue number in absolute terms, that is consecutive residues have consecutive numbers that reset when there is a segment change. (What to do when 5 digits are exceeded? Star solution "*****" or create new segment?)

b) Keep the original numbering.

Ideally we could implement it so the user can choose a different option for each segment.

**Comment by Kloppel** [comment]
I will close this and add to #6 so that we have a better overview.
